CREATE TABLE "SPANISH" (
	`WORD`	TEXT NOT NULL,
	`TL1`	TEXT NOT NULL,
	`TL2`	TEXT,
	`TL3`	TEXT,
	`NIVEL`	INTEGER NOT NULL,
	`TIPO`	TEXT NOT NULL
);
INSERT INTO `SPANISH` (WORD,TL1,TL2,TL3,NIVEL,TIPO) VALUES ('anchovy','boquerón','anchoa','',1,'food'),
 ('Apple','Manzana','','',1,'food'),
 ('Banana','Plátano','Banana','',1,'food'),
 ('beer','cerveza','','',1,'food'),
 ('bread','pan','','',1,'food'),
 ('Burger','hamburguesa','','',1,'food'),
 ('Cherries','Cerezas','','',1,'food'),
 ('Cherry','Cereza','','',1,'food'),
 ('Chicken','pollo','','',1,'food'),
 ('chickpea','garbanzo','','',1,'food'),
 ('cod','bacalao','','',1,'food'),
 ('Eggs','huevos','','',1,'food'),
 ('Fideua','fideuá','','',1,'food'),
 ('flan','flan','','',1,'food'),
 ('Garlic','Ajo','','',1,'food'),
 ('green beans','judías verdes','','',1,'food'),
 ('hake','merluza','pescada','',1,'food'),
 ('juice','zumo','','',1,'food'),
 ('Kiwi','Kiwi','','',1,'food'),
 ('macaroni','macarrones','','',1,'food'),
 ('noodles','fideos','','',1,'food'),
 ('Onion','Cebolla','','',1,'food'),
 ('Paella','paella','','',1,'food'),
 ('Papaya','Papaya','','',1,'food'),
 ('Pear','Pera','','',1,'food'),
 ('Pizza','pizza','','',1,'food'),
 ('potage','potaje','','',1,'food'),
 ('proteins','proteínas','','',1,'food'),
 ('pumpkin','calabaza','','',1,'food'),
 ('Ravioli','raviolis','','',1,'food'),
 ('salmorejo','salmorejo','','',1,'food'),
 ('Soup','sopa','','',1,'food'),
 ('spaghetti','espaguetis','','',1,'food'),
 ('squid','calamar','','',1,'food'),
 ('Strawberry','Fresa','','',1,'food'),
 ('swordfish','emperador','','',1,'food'),
 ('Tiramisu','tiramisú','','',1,'food'),
 ('Tomato','Tomate','','',1,'food'),
 ('trout','trucha','','',1,'food'),
 ('Turkey','pavo','','',1,'food'),
 ('Vegetable','Vegetal','Verdura','',1,'food'),
 ('Water','agua','','',1,'food'),
 ('wholemeal bread','pan integral','','',1,'food'),
 ('Broccoli','Brócoli','','',1,'food'),
 ('cabbage','repollo','','',1,'food'),
 ('calories','calorías','','',1,'food'),
 ('Carrot','Zanahoria','','',1,'food'),
 ('cauliflower','Coliflor','','',1,'food'),
 ('cheese','queso','','',1,'food'),
 ('chips','patatas fritas','','',1,'food'),
 ('clams','almejas','','',1,'food'),
 ('Empanadillas','empanadillas','','',1,'food'),
 ('endive','escarola','','',1,'food'),
 ('fat','grasas','gordo','',1,'food'),
 ('green peas','guisantes','','',1,'food'),
 ('Lamb','cordero','','',1,'food'),
 ('lentils','lentejas','','',1,'food'),
 ('Lettuce','Lechuga','','',1,'food'),
 ('lobster','langosta','','',1,'food'),
 ('Lubina','lubina','','',1,'food'),
 ('mussels','mejillones','','',1,'food'),
 ('omelette','tortilla francesa','tortilla','',1,'food'),
 ('Peach','Melocotón','','',1,'food'),
 ('Plum','Ciruela','','',1,'food'),
 ('Pork','cerdo','','',1,'food'),
 ('prawns','gambas','','',1,'food'),
 ('rabbit','conejo','','',1,'food'),
 ('Red pepper','Pimiento rojo','','',1,'food'),
 ('rice','arroz','','',1,'food'),
 ('rice pudding','arroz con leche','','',1,'food'),
 ('sardine','sardina','','',1,'food'),
 ('Spanish omelette','tortilla de patatas','','',1,'food'),
 ('Spinach','Espinacas','','',1,'food'),
 ('Tortelini','tortelini','','',1,'food'),
 ('Watermelon','Sandía','Melón de agua','',1,'food'),
 ('wine','vino','','',1,'food'),
 ('Zucchini','Calabacín','','',1,'food'),
 ('oregano','orégano','','',1,'food'),
 ('pepper','pimienta','','',1,'food'),
 ('Avocado','Aguacate','','',2,'food'),
 ('Biscuit','bizcocho','galleta','',2,'food'),
 ('biscuits','galletas','','',2,'food'),
 ('Cantaloupe','Melón','','',2,'food'),
 ('chard','Acelgas','','',2,'food'),
 ('Cooked','cocido','','',2,'food'),
 ('eggplant','Berenjena','','',2,'food'),
 ('football','fútbol','balonpié','',2,'food'),
 ('green pepper','Pimiento verde','','',2,'food'),
 ('handball','balónmano','','',2,'food'),
 ('Leek','Puerro','','',2,'food'),
 ('red mullets','salmonetes','','',2,'food'),
 ('red sea bream','besugo','','',2,'food'),
 ('rye','centeno','','',2,'food'),
 ('sausage','salchichón','chorizo','salchichas',2,'food'),
 ('stop watch','cronómetro','','',2,'food'),
 ('turnip','Nabo','','',2,'food'),
 ('Veal','ternera','','',2,'food'),
 ('vitamins','vitaminas','','',2,'food'),
 ('alfalfa','alfalfa','','',2,'food'),
 ('aniseed','anís','','',2,'food'),
 ('cayenne','pimienta de cayena','cayena','',2,'food'),
 ('rosemary','romero','','',2,'food'),
 ('candies','caramelos','','',2,'food'),
 ('carbohydrates','hidratos de carbono','carbohidratos','',2,'food'),
 ('Cranberry','Arándano','','',2,'food'),
 ('Ham','jamón','','',2,'food'),
 ('minerals','minerales','','',2,'food'),
 ('muffin','magdalenas','','',2,'food'),
 ('snack','bocadillo','','',2,'food'),
 ('York ham','jamón york','','',2,'food'),
 ('mint','menta','','',2,'food'),
 ('nutmeg','nuez moscada','','',2,'food'),
 ('valerian','valeriana','','',2,'food'),
 ('crabs','cangrejos','','',3,'food'),
 ('Steaks','filetes','','',3,'food'),
 ('drinks','refrescos','','',3,'food'),
 ('mortadella','mortadela','','',3,'food'),
 ('Raspberry','Frambuesa','','',3,'food'),
 ('salmon','salmón','','',3,'food'),
 ('lemongrass','citronela','','',3,'food'),
 ('paprika','pimentón','','',3,'food'),
 ('loin','lomo','','',4,'food'),
 ('vegetables cream','crema de verduras','','',4,'food'),
 ('saffron','azafrán','','',4,'food'),
 ('coriander','cilantro','','',4,'food'),
 ('parsley','perejil','','',4,'food'),
 ('clover','trébol','','',4,'food'),
 ('red clover','trébol rojo','','',4,'food'),
 ('custard','natilllas','','',4,'food'),
 ('Neapolitan','napolitanas','','',4,'food'),
 ('Patty','empanada','','',4,'food'),
 ('camomile','camomila','','',4,'food'),
 ('cinnamon','canela','','',4,'food'),
 ('chives','cebolletas','','',4,'food'),
 ('spice','especia','','',4,'food'),
 ('elderberry','saúco','','',4,'food'),
 ('thyme','tomillo','','',4,'food'),
 ('Quince','Membrillo','','',5,'food'),
 ('radish','rábano','','',5,'food'),
 ('fennel','hinojo','','',5,'food'),
 ('hyssop','hisopo','','',5,'food'),
 ('ginseng','ginseng','','',5,'food'),
 ('bay','laurel','','',5,'food'),
 ('sage','salvia','','',5,'food'),
 ('basil','albahaca','','',5,'food'),
 ('chicory','achicoria','endivia','',5,'food'),
 ('yarrow','aquilea','','',5,'food'),
 ('cumin','comino','','',5,'food'),
 ('turmeric','cúrcuma','','',5,'food'),
 ('dandelion','diente de león','','',5,'food'),
 ('juniper','enebro','','',5,'food'),
 ('dill','eneldo','','',5,'food'),
 ('tarragon','estragón','','',5,'food'),
 ('marjoram','mejorana','','',5,'food'),
 ('nettle','ortiga','','',5,'food'),
 ('chervil','perifollo','','',5,'food'),
 ('badminton','badminton','bádminton','',1,'sport'),
 ('basketball','baloncesto','','',1,'sport'),
 ('golf','golf','','',1,'sport'),
 ('hockey','hockey','','',1,'sport'),
 ('judo','judo','','',1,'sport'),
 ('karate','karate','','',1,'sport'),
 ('rugby','rugby','','',1,'sport'),
 ('ski','esquí','','',1,'sport'),
 ('skiing','esquí','','',1,'sport'),
 ('squash','squash','','',1,'sport'),
 ('yoga','yoga','','',1,'sport'),
 ('football','fútbol','','',1,'sport'),
 ('game','juego','','',1,'sport'),
 ('competition','competición','','',1,'sport'),
 ('win','victoria','','',1,'sport'),
 ('loss','derrota','','',1,'sport'),
 ('victory','victoria','','',1,'sport'),
 ('defeat','derrota','','',1,'sport'),
 ('bicycle','bicicleta','','',1,'sport'),
 ('boxing','boxeo','','',1,'sport'),
 ('cycling','ciclismo','','',1,'sport'),
 ('gymnastics','gimnasia','','',1,'sport'),
 ('ice hockey','hockey sobre hielo','','',1,'sport'),
 ('jogging','hacer jogging','jogging','correr',1,'sport'),
 ('kick boxing','kick boxing','','',1,'sport'),
 ('neoprene','neopreno','','',1,'sport'),
 ('Run','Correr','','',1,'sport'),
 ('running','correr','','',1,'sport'),
 ('surfing','surf','','',1,'sport'),
 ('swimming','natación','','',1,'sport'),
 ('tennis','tenis','','',1,'sport'),
 ('volleyball','voleibol','','',1,'sport'),
 ('water polo','waterpolo','','',1,'sport'),
 ('windsurfing','windsurf','','',1,'sport'),
 ('ball','pelota','','',1,'sport'),
 ('football boots','botas de fútbol','','',1,'sport'),
 ('marathon','maratón','','',1,'sport'),
 ('to play','jugar','','',1,'sport'),
 ('to win','ganar','','',1,'sport'),
 ('to lose','perder','','',1,'sport'),
 ('match','partido','','',1,'sport'),
 ('league table','clasificación','','',1,'sport'),
 ('loser','perdedor/a','','',1,'sport'),
 ('spectator','espectador/a','','',1,'sport'),
 ('draw','empate','','',1,'sport'),
 ('Olympic Games','Juegos Olímpicos','','',1,'sport'),
 ('to ride a bicycle o to ride a bike','montar en bicicleta','','',1,'sport'),
 ('boots','botas','','',2,'sport'),
 ('darts','dardos','','',2,'sport'),
 ('ice skating','patinaje sobre hielo','','',2,'sport'),
 ('motor racing','carreras de coches','','',2,'sport'),
 ('mountain climbing','alpinismo','escalar montañas','',2,'sport'),
 ('sailing','vela','navegar','',2,'sport'),
 ('socks','calcetines','','',2,'sport'),
 ('sport shoes','zapatillas','zapatillas de deporte','',2,'sport'),
 ('surfboard','tabla de surf','','',2,'sport'),
 ('Walk','Andar','Caminar','Marchar',2,'sport'),
 ('walking','caminar','','',2,'sport'),
 ('to draw','empatar','','',2,'sport'),
 ('to watch','ver','','',2,'sport'),
 ('score','marcador','','',2,'sport'),
 ('winner','ganador/a','','',2,'sport'),
 ('to play away','jugar fuera','','',2,'sport'),
 ('to play at home','jugar en casa','','',2,'sport'),
 ('chain','cadena','','',2,'sport'),
 ('gears','marchas','','',2,'sport'),
 ('baseball','béisbol','','',2,'sport'),
 ('beach volleyball','voley playa','','',2,'sport'),
 ('cricket','críquet','','',2,'sport'),
 ('water skiing','esquí acuático','','',2,'sport'),
 ('wrestling','wrestling','lucha','lucha libre',2,'sport'),
 ('fishing rod','caña de pescar','','',2,'sport'),
 ('hammer throw','lanzamiento de martillo','','',2,'sport'),
 ('high jump','salto de altura','','',2,'sport'),
 ('result','resultado','','',2,'sport'),
 ('opponent','oponente','','',2,'sport'),
 ('canoeing','piragüismo','','',3,'sport'),
 ('climbing','escalada','escalar','',3,'sport'),
 ('fishing','pesca','','',3,'sport'),
 ('hunting','caza','','',3,'sport'),
 ('martial arts','artes marciales','','',3,'sport'),
 ('pool','billar','','',3,'sport'),
 ('shooting','tiro','','',3,'sport'),
 ('snowboarding','snowboard','','',3,'sport'),
 ('badminton racquet','raqueta de bádminton','','',3,'sport'),
 ('baseball bat','bate de béisbol','','',3,'sport'),
 ('boxing glove','guante de boxeo','','',3,'sport'),
 ('squash racquet','raqueta de squash','','',3,'sport'),
 ('tennis racquet','raqueta de tenis','','',3,'sport'),
 ('discus throw','lanzamiento de disco','','',3,'sport'),
 ('triple jump','triple salto','','',3,'sport'),
 ('pedal','pedal','','',3,'sport'),
 ('puncture','pinchazo','','',3,'sport'),
 ('puncture repair kit','juego de herramientas para reparar un pinchazo','','',3,'sport'),
 ('diving','submarinismo','','',3,'sport'),
 ('hiking','hacer senderismo','','',3,'sport'),
 ('horse racing','carrera de caballos','','',3,'sport'),
 ('horse riding','montar a caballo','','',3,'sport'),
 ('inline skating','patinaje en línea','','',3,'sport'),
 ('mountaineering','montañismo','alpinismo','escalar montañas',3,'sport'),
 ('rowing','remo','','',3,'sport'),
 ('running shoes','zapatillas para correr','','',3,'sport'),
 ('skateboard','tabla de skateboard','','',3,'sport'),
 ('skis','esquíes','','',3,'sport'),
 ('bicycle pump','bomba de bicicleta','','',3,'sport'),
 ('tyre','neumático','','',3,'sport'),
 ('go-karting','karting','','',4,'sport'),
 ('heart rate monitor','pulsómetro','monitor de pulso','',4,'sport'),
 ('lacrosse','lacrosse','','',4,'sport'),
 ('skateboarding','skateboard','','',4,'sport'),
 ('skating','patinaje','','',4,'sport'),
 ('hockey stick','stick de hockey','','',4,'sport'),
 ('ice skates','patines de hielo','','',4,'sport'),
 ('pool cue','taco de billar','','',4,'sport'),
 ('rugby ball','pelota de rugby','','',4,'sport'),
 ('fixture','encuentro','','',4,'sport'),
 ('to have a puncture','sufrir un pinchazo','','',4,'sport'),
 ('raincoat','chubasquero','','',4,'sport'),
 ('table tennis','tenis de mesa','','',4,'sport'),
 ('track and field','atletismo','','',4,'sport'),
 ('weightlifting','halterofilia','','',4,'sport'),
 ('golf club','club de golf','palo de golf','',4,'sport'),
 ('referee','árbitro','','',4,'sport'),
 ('brake','freno','','',4,'sport'),
 ('inner tube','cámara de la rueda','','',4,'sport'),
 ('scuba diving','buceo','','',5,'sport'),
 ('snooker','snooker','','',5,'sport'),
 ('syncronized swimming','natación sincronizada','','',5,'sport'),
 ('ten-pin bowling','bolos','','',5,'sport'),
 ('javelin throw','lanzamiento de jabalina','','',5,'sport'),
 ('long jump','salto de longitud','','',5,'sport'),
 ('pole vault','salto de pértiga','','',5,'sport'),
 ('shot put','lanzamiento de peso','','',5,'sport'),
 ('umpire','árbitro','juez de silla','réferi',5,'sport'),
 ('handlebars','manillar','','',5,'sport'),
 ('wheel','rueda','','',5,'sport'),
 ('archery','tiro con arco','','',5,'sport'),
 ('bowls','bolos','','',5,'sport'),
 ('hurdles','vallas','','',5,'sport'),
 ('cricket bat','bate de críquet','','',5,'sport'),
 ('saddle','sillín','','',5,'sport'),
 ('spokes','radios','','',5,'sport'),
 ('sorrel','acedera','','',5,'sport'),
 ('horsetail','cola de caballo','','',5,'sport');
CREATE TABLE "POLISH" (
	`WORD`	TEXT NOT NULL,
	`TL1`	TEXT NOT NULL,
	`TL2`	TEXT,
	`TL3`	TEXT,
	`NIVEL`	INTEGER NOT NULL,
	`TIPO`	TEXT NOT NULL
);
INSERT INTO `POLISH` (WORD,TL1,TL2,TL3,NIVEL,TIPO) VALUES ('anchovies','anszua','','',1,'FOOD'),
 ('caviar','kawior','','',1,'FOOD'),
 ('crayfish','langusta','','',1,'FOOD'),
 ('homar','homar','','',1,'FOOD'),
 ('octopus','ośmiornica','','',1,'FOOD'),
 ('squid','kałamarnica','','',1,'FOOD'),
 ('amino acid','aminokwas','','',1,'FOOD'),
 ('carbohydrates','węglowodany','','',1,'FOOD'),
 ('vitamins','witaminy','','',1,'FOOD'),
 ('calorie','kaloria','','',1,'FOOD'),
 ('cholesterol','cholesterol','','',1,'FOOD'),
 ('powdered milk','mleko w proszku','','',1,'FOOD'),
 ('almond','migdał','','',1,'FOOD'),
 ('brazil nut','orzech brazylijski','','',1,'FOOD'),
 ('cashew','orzech nerkowca','','',1,'FOOD'),
 ('raisin','rodzynka','','',1,'FOOD'),
 ('coconut','kokos','orzech kokosowy','',2,'FOOD'),
 ('ammonia','amoniak','','',1,'FOOD'),
 ('baking powder','proszek do pieczenia','','',1,'FOOD'),
 ('yeast','drożdże','','',1,'FOOD'),
 ('breadcrumbs','bułka tarta','','',1,'FOOD'),
 ('icing sugar','cukier puder','','',1,'FOOD'),
 ('aniseed','anyż','anyżek','',1,'FOOD'),
 ('basil','bazylia','','',1,'FOOD'),
 ('chamomile','rumianek','rumiankowy','',2,'FOOD'),
 ('chive','szczypiorek','','',1,'FOOD'),
 ('coriander','kolendra','','',1,'FOOD'),
 ('cress','rzeżucha','','',1,'FOOD'),
 ('dill','koper','koperek','',2,'FOOD'),
 ('appetite','apetyt','łaknienie','',1,'FOOD'),
 ('appetizing','apetyczny','smakowity','smaczny',1,'FOOD'),
 ('aroma','zapach','aromat','aromatyczny',3,'FOOD'),
 ('aromatic','aromatyczny','','',1,'FOOD'),
 ('aspic','galareta','','',1,'FOOD'),
 ('bag lunch','drugie śniadanie','kanapki','lunch na wynos',3,'FOOD'),
 ('box lunch','lunch w pudełku','drugie śniadanie','lunch na wynos',3,'FOOD'),
 ('packed lunch','zapakowany lunch','drugie śniadanie','lunch na wynos',3,'FOOD'),
 ('bite','gryźć','','',1,'FOOD'),
 ('bon apetit','smacznego','','',1,'FOOD'),
 ('bone','kość','obierać mięso z kości','',2,'FOOD'),
 ('bone','ość','obierać rybę z ości','',2,'FOOD'),
 ('breaded','panierowany','','',1,'FOOD'),
 ('caffeine','kofeina','','',1,'FOOD'),
 ('creamy','kremowy','gęsty','śmietankowy',3,'FOOD'),
 ('crisps','czipsy','chipsy','',1,'fOOD'),
 ('crispy','kruche','chrupiące','',2,'fOOD'),
 ('delicious','pyszne','','',1,'FOOD'),
 ('dressing','sos sałatkowy','','',1,'FOOD'),
 ('yummy','pyszne','','',1,'FOOD'),
 ('yucky','wstretne','paskudne','okropne',3,'FOOD'),
 ('apricot','morela','','',1,'FOOD'),
 ('blackcurrant','czarna porzeczka','','',1,'FOOD'),
 ('artichoke','karczoch','','',1,'FOOD'),
 ('asparagus','szparagi','','',1,'FOOD'),
 ('baked beans','fasolka w sosie pomidorowym','fasolka po bretońsku','',2,'FOOD'),
 ('baked potato','ziemniak w mundurku','pieczony ziemniak','',2,'FOOD'),
 ('jacket potato','ziemniak w mundurku','pieczony ziemniak','',2,'FOOD'),
 ('green bean','zielona fasolka','fasolka szparagowa','',2,'FOOD'),
 ('soya bean','soja','','',1,'FOOD'),
 ('broad bean','bób','','',2,'FOOD'),
 ('bean sprouts','kiełki fasoli','','',1,'FOOD'),
 ('bagel','bajgiel','obwarzanek','',2,'FOOD'),
 ('bread and butter','chleb z masłem','','',1,'FOOD'),
 ('baker','piekarz','cukiernia','piekarnia',3,'FOOD'),
 ('apron','fartuch','fartuszek','',2,'FOOD'),
 ('banger','kiełbaska','kiełbasa','',2,'FOOD'),
 ('beefburger','kotlet mielony wołowy','','',1,'FOOD'),
 ('starter','przystawka','','',1,'FOOD'),
 ('beverage','napój','','',1,'FOOD'),
 ('bill','rachunek','','',1,'FOOD'),
 ('main course','danie głowne','pierwsze danie','',2,'FOOD'),
 ('soup','zupa','','',1,'FOOD'),
 ('dessert','deser','','',1,'FOOD'),
 ('menu','menu','jadłospis','karta dań',3,'FOOD'),
 ('waiter','kelner','','',1,'FOOD'),
 ('waitress','kelnerka','','',1,'FOOD'),
 ('chef','szef kuchni','','',1,'FOOD'),
 ('cook','kucharz','','',1,'FOOD'),
 ('customer','klient','','',1,'FOOD'),
 ('takeaway','danie na wynos','na wynos','',1,'FOOD'),
 ('order','zamówić','','',1,'FOOD'),
 ('pay by credit card','płacić kartą kredytową','','',1,'FOOD'),
 ('boiling point','temeratura wrzenia','','',1,'FOOD'),
 ('braise','dusić','gotować na wolnym ogniu','',2,'FOOD'),
 ('bottle opener','otwieracz do butelek','','',1,'FOOD'),
 ('can opener','otwieracz do konserw','','',1,'FOOD'),
 ('tin opener','otwieracz do konserw','','',1,'FOOD'),
 ('chopsticks','pałeczki','','',1,'FOOD'),
 ('corkscrew','korkociag','','',1,'FOOD'),
 ('crockery','naczynia','porcelana','zastawa stołowa',3,'FOOD'),
 ('bouillon','bulion','rosół','',2,'FOOD'),
 ('broth','gęsta zupa','','',2,'FOOD'),
 ('breakfast','śniadanie','','',1,'FOOD'),
 ('lunch','drugie śniadanie','lunch','obiad',3,'FOOD'),
 ('brunch','połączenie śniadania z lunchem','','',1,'FOOD'),
 ('dinner','obiad','kolacja','',2,'FOOD'),
 ('tea','podwieczorek','herbatka','',2,'FOOD'),
 ('supper','kolacja','','',1,'FOOD'),
 ('buffet','bufet','','',1,'FOOD'),
 ('restaurant','restauracja','','',1,'FOOD'),
 ('cafe','kawiarnia','herbaciarnia','',2,'FOOD'),
 ('canteen','kantyna','stołówka','',2,'FOOD'),
 ('diner','stołówka','jadłodalnia','',2,'FOOD'),
 ('buffet car','wagon restauracyjny','','',1,'FOOD'),
 ('butcher','rzeźnik','sklep mięsny','',2,'FOOD'),
 ('cafeteria','stołówka','bufet','kantyna',3,'FOOD'),
 ('coffee bar/shop','bar kawowy','','',1,'FOOD'),
 ('delicatessen','delikatesy','','',1,'FOOD'),
 ('can','puszka','','',1,'FOOD'),
 ('tin','konserwa','','',1,'FOOD'),
 ('carafe','karafka','','',1,'FOOD'),
 ('carton','karton','','',1,'FOOD'),
 ('abseil','spuszczać się na linie','','',2,'SPORT'),
 ('attack','atakować','','',1,'SPORT'),
 ('award','nagradzać','przyznawać nagrodę','',2,'SPORT'),
 ('backpack','uprawiać turystykę pieszą','','',1,'SPORT'),
 ('back-pedal','pedałować do tyłu','','',1,'SPORT'),
 ('beat','pokonać','','',1,'SPORT'),
 ('canoe','pływać kajakiem','','',1,'SPORT'),
 ('climb','wspinać się','','',1,'SPORT'),
 ('compete','współzawodniczyć','rywalizować','konkurować',3,'SPORT'),
 ('cycle','jechać na rowerze','','',1,'SPORT'),
 ('defend','bronić','','',1,'SPORT'),
 ('do aerobics','ćwiczyć aerobik','','',1,'SPORT'),
 ('dribble','kozłować','odbijać','',2,'SPORT'),
 ('exercise','ćwiczyc','gimnastykować się','',2,'SPORT'),
 ('go by bike','jechać rowerem','','',1,'SPORT'),
 ('go jogging','iść pobiegac','','',1,'SPORT'),
 ('go swimming','iść popływać','','',1,'SPORT'),
 ('jog','biegac','','',1,'SPORT'),
 ('jump','skakać','','',1,'SPORT'),
 ('kick','kopać','','',1,'SPORT'),
 ('pass','podać','podawać','',2,'SPORT'),
 ('play baseball','grac w baseball','','',1,'SPORT'),
 ('play basketball','grać w koszykówkę','','',1,'SPORT'),
 ('play chess','grać w szachy','','',1,'SPORT'),
 ('play football','grać w piłkę nożną','','',1,'SPORT'),
 ('play handball','grać w piłkę ręczną','','',1,'SPORT'),
 ('play hockey','grać w hokeja','','',1,'SPORT'),
 ('play rugby','grać w rugby','','',1,'SPORT'),
 ('play volleyball','grać w siatkówkę','','',1,'SPORT'),
 ('ride a bike','jeździć na rowerze','','',1,'SPORT'),
 ('row','wiosłować','','',1,'SPORT'),
 ('run','biegać','','',1,'SPORT'),
 ('tackle','kiwać','blokować','chwytać',1,'SPORT'),
 ('walk','iść','spacerować','',2,'SPORT'),
 ('abseiling','spuszczanie się na linie','','',1,'SPORT'),
 ('acrobatics','akrobatyka','','',1,'SPORT'),
 ('aerobics','aerobik','','',1,'SPORT'),
 ('American footbal','footbal amerykański','','',1,'SPORT'),
 ('archery','łucznictwo','','',1,'SPORT'),
 ('athletics','lekkoatletyka','','',1,'SPORT'),
 ('backpacking','turystyka piesza z plecakiem','','',1,'SPORT'),
 ('backstroke','styl grzbietowy','pływać grzbietem','',2,'SPORT'),
 ('badminton','badminton','kometka','',2,'SPORT'),
 ('basketball','koszykówka','','',1,'SPORT'),
 ('baseball','baseball','','',1,'SPORT'),
 ('board game','gra planszowa','','',1,'SPORT'),
 ('bodybuilding','kulturystyka','','',1,'SPORT'),
 ('bowling','gra w kręgle','','',1,'SPORT'),
 ('boxing','boks','','',1,'SPORT'),
 ('breaststroke','styl klasyczny','żabka','',2,'SPORT'),
 ('butterfly','styl motylkowy','','',1,'SPORT'),
 ('canoeing','kajakarstwo','pływanie kajakiem','',2,'SPORT'),
 ('checkers','warcaby','','',1,'SPORT'),
 ('crawl','kraul','pływanie kraulem','',2,'SPORT'),
 ('cricket','krykiet','','',1,'SPORT'),
 ('cycling','kolarstwo','','',1,'SPORT'),
 ('draughts','warcaby','','',1,'SPORT'),
 ('fencing','szermierka','fechtunek','',2,'SPORT'),
 ('field tennis','tenis','','',1,'SPORT'),
 ('football','piłka nożna','','',1,'SPORT'),
 ('golf','golf','','',1,'SPORT'),
 ('gymnastics','gimnastyka','','',1,'SPORT'),
 ('handball','piłka ręczna','','',1,'SPORT'),
 ('hockey','hokej','','',1,'SPORT'),
 ('horse racing','wyścigi konne','','',1,'SPORT'),
 ('judo','dżudo','','',1,'SPORT'),
 ('kayaking','kajakarstwo','pływanie kajakiem','',2,'SPORT'),
 ('lacrosse','lakros','','',1,'SPORT'),
 ('marathon','maraton','','',1,'SPORT'),
 ('parachuting','skoki spadochronowe','','',1,'SPORT'),
 ('polo','polo','','',1,'SPORT'),
 ('rowing','wioślarstwo','','',1,'SPORT'),
 ('rugby','rugby','','',1,'SPORT'),
 ('sailing','żeglarstwo','','',1,'SPORT'),
 ('skateboarding','jazda na deskorolce','','',1,'SPORT'),
 ('skating','łyżwiarstwo','','',1,'SPORT'),
 ('skiiing','narciarstwo','','',1,'SPORT'),
 ('skydiving','skoki spadochronowe','','',1,'SPORT'),
 ('snowboarding','snowboarding','','',1,'SPORT'),
 ('sprint','sprint','','',1,'SPORT'),
 ('surfing','pływanie na desce surfingowej','','',1,'SPORT'),
 ('swimming','pływanie','','',1,'SPORT'),
 ('table tennis','tenis stołowy','','',1,'SPORT'),
 ('triathlon','triatlon','','',1,'SPORT'),
 ('valleyball','siatkówka','piłka siatkowa','',2,'SPORT'),
 ('weightlifting','podnoszenie ciężarów','','',1,'SPORT'),
 ('wingsuit','latanie w kombinezonie','','',1,'SPORT'),
 ('white-water rafting','spływ górski','','',1,'SPORT'),
 ('workout','trening','zaprawa fizyczna','',2,'SPORT'),
 ('yoga','joga','','',1,'SPORT'),
 ('backpack','plecak do wędrówek','','',1,'SPORT'),
 ('ballpark','boisko baseballowe','','',1,'SPORT'),
 ('baseball','piłka koszykowa','piłka do koszykówki','',2,'SPORT'),
 ('baseball bat','kij baseballowy','','',1,'SPORT'),
 ('baseball glove','rękawica baseballowa','','',1,'SPORT'),
 ('basket','kosz','','',1,'SPORT'),
 ('basketball','piłka baseballowa','piłka do baseballu','',2,'SPORT'),
 ('bat','rakietka do tenisa stołowego','kij baseballowy','kij do krykieta',3,'SPORT'),
 ('bicycle','rower','','',1,'SPORT'),
 ('bike','rower','motocykl','',2,'SPORT'),
 ('bobsleigh','bobslej','sanki','',2,'SPORT'),
 ('bow','łuk','','',1,'SPORT'),
 ('boxing gloves','rękawice bokserskie','','',1,'SPORT'),
 ('canoe','kajak','','',1,'SPORT'),
 ('exercise bike','rower treningowy','','',1,'SPORT'),
 ('foil','floret','','',1,'SPORT'),
 ('football','piłka nożna','piłka do footballu','',2,'SPORT'),
 ('golf club','kij golfowy','','',1,'SPORT'),
 ('handball','piłka do ręcznej','','',1,'SPORT'),
 ('helmet','kask','','',1,'SPORT'),
 ('hockey puck','krążek do hokeja','krążek hokejowy','',2,'SPORT'),
 ('hockey stick','kij hokejowy','','',1,'SPORT'),
 ('horse','koń','','',1,'SPORT'),
 ('jockey cap','toczek do jazdy konnej','','',1,'SPORT'),
 ('jump','przeszkoda','','',1,'SPORT'),
 ('kayak','kajak','','',1,'SPORT'),
 ('mask','maska','','',1,'SPORT'),
 ('net','siatka','','',1,'SPORT'),
 ('paddle','wiosło','','',1,'SPORT'),
 ('parachute','spadochron','','',1,'SPORT'),
 ('quanco','piłka do rugby','','',1,'SPORT'),
 ('racket','rakieta','','',1,'SPORT'),
 ('saddle','siodło','','',1,'SPORT'),
 ('sail','żagiel','','',1,'SPORT'),
 ('sailboat','żaglówka','','',1,'SPORT'),
 ('shuttlecock','lotka do badmintona','','',1,'SPORT'),
 ('skateboard','deskorolka','','',1,'SPORT'),
 ('skates','łyżwy','','',1,'SPORT'),
 ('skis','narty','','',1,'SPORT'),
 ('ski poles','kijki narciarskie','','',1,'SPORT'),
 ('snowboard','deska do snowboardu','','',1,'SPORT'),
 ('surfboard','deska surfingowa','','',1,'SPORT'),
 ('swimsuit','kostium pływacki','','',1,'SPORT'),
 ('swimming cap','czepek pływacki','','',1,'SPORT'),
 ('swimming trunks','kąpielówki','','',1,'SPORT'),
 ('target','cel','tarcza','',2,'SPORT'),
 ('tracksuit','dres','','',1,'SPORT'),
 ('trainers','butry sportowe','adidasy','',1,'SPORT'),
 ('weight','ciężar','ciężarek','',2,'SPORT'),
 ('wingsuit','kombinezon do latania','','',1,'SPORT'),
 ('yacht','jacht','','',1,'SPORT'),
 ('acrobat','akrobata','akrobatka','',1,'SPORT'),
 ('adversary','przeciwnik','przeciwniczka','rywal',1,'SPORT'),
 ('arbiter','arbiter','','',1,'SPORT'),
 ('archer','łucznik','łuczniczka','',1,'SPORT'),
 ('athlete','lekkoatleta','sportowiec','',2,'SPORT'),
 ('attacker','napastnik','','',1,'SPORT'),
 ('backpacker','turysta uprawiający wędrówkę pieszą','','',1,'SPORT'),
 ('baseplayer','biegacz','','',1,'SPORT'),
 ('biker','rowerzysta','cyklista','motocyklista',3,'SPORT'),
 ('bodybuilder','kulturysta','kulturystka','',1,'SPORT'),
 ('boxer','bokser','','',1,'SPORT'),
 ('catcher','łapacz','','',1,'SPORT'),
 ('champion','mistrz','mistrzyni','czempion',3,'SPORT'),
 ('coach','trener','','',1,'SPORT'),
 ('commenter','komentator','','',1,'SPORT'),
 ('competitor','zawodnik','przeciwnik','współzawodnik',3,'SPORT'),
 ('contestant','zawodnik','','',1,'SPORT'),
 ('cricketer','gracz w krykieta','','',1,'SPORT'),
 ('cyclist','rowerzysta','cyklista','',2,'SPORT'),
 ('defender','obrońca','','',1,'SPORT'),
 ('fan','kibic','fan','',2,'SPORT'),
 ('fencer','szermierz','','',1,'SPORT'),
 ('goalkeeper','bramkarz','','',1,'SPORT'),
 ('gymnast','gimnastyk','','',1,'SPORT'),
 ('jockey','dżokej','','',1,'SPORT'),
 ('parachuter','spadochroniarz','','',1,'SPORT'),
 ('pitcher','zawodnik rzucający piłką','miotacz','',2,'SPORT'),
 ('player','gracz','zawodnik','uczestnik',3,'SPORT'),
 ('refree','sędzia','','',1,'SPORT'),
 ('runner','biegacz','','',1,'SPORT'),
 ('skater','łyżwiarz','','',1,'SPORT'),
 ('skiier','narciarz','','',1,'SPORT'),
 ('ski jumper','skoczek narciarski','','',1,'SPORT'),
 ('sprinter','sprinter','','',1,'SPORT'),
 ('supporter','kibic','pomocnik','',2,'SPORT'),
 ('surfer','serfer','','',1,'SPORT'),
 ('umpire','sędzia','','',1,'SPORT'),
 ('winner','zwycięzca','','',1,'SPORT'),
 ('able-bodied','zdrowy fizycznie','pełnosprawny','',2,'SPORT'),
 ('ace','as','as serwisowy','',2,'SPORT'),
 ('acrobatic','akrobatyczny','','',1,'SPORT'),
 ('adrenalin','adrenalina','','',1,'SPORT'),
 ('alpine','alpejski','wysokogórski','',2,'SPORT'),
 ('amateur','amator','amatorka','',1,'SPORT'),
 ('ascent','wspinaczka','','',1,'SPORT'),
 ('athletic','wysportowany','lekkoatletyczny','spotowy',3,'SPORT'),
 ('attack','atak','','',1,'SPORT'),
 ('audience','publiczność','widownia','',2,'SPORT'),
 ('award','nagroda','','',1,'SPORT'),
 ('backhand','bekhend','','',1,'SPORT'),
 ('biceps','biceps','','',1,'SPORT'),
 ('bikini','dwuczęściowy kostium kąpielowy','bikini','',2,'SPORT'),
 ('bronze medal','brązowy medal','','',1,'SPORT'),
 ('championship','mistrzostwo','','',1,'SPORT'),
 ('checkmate','szach mat','','',1,'SPORT'),
 ('competition','rywalizacja','konkurencja','konkurs',3,'SPORT'),
 ('competitive','konkurencyjny','','',1,'SPORT'),
 ('contest','zawody','konkurs','',2,'SPORT'),
 ('tournament','zawody sportowe','rozgrywki sportowe','',2,'SPORT'),
 ('defence','obrona','','',1,'SPORT'),
 ('disabled','niepełnosprawny','','',1,'SPORT'),
 ('fit','sprawny','','',1,'SPORT'),
 ('physical activity','aktywność fizyczna','','',1,'SPORT'),
 ('stadium','stadion','','',1,'SPORT'),
 ('cross country','przełajowy (bieg)','','',1,'SPORT'),
 ('downhill','zjazdowe (narciarstwo)','','',1,'SPORT');
CREATE TABLE "GERMAN" (
	`WORD`	TEXT NOT NULL,
	`TL1`	TEXT NOT NULL,
	`TL2`	TEXT,
	`TL3`	TEXT,
	`NIVEL`	INTEGER NOT NULL,
	`TIPO`	TEXT NOT NULL
);
INSERT INTO `GERMAN` (WORD,TL1,TL2,TL3,NIVEL,TIPO) VALUES ('to serve','aufschlagen','bedienen','',2,'sport'),
 ('net','Netz','','',1,'sport'),
 ('to jump','springen','','',1,'sport'),
 ('to block','blocken','verteidigen','',1,'sport'),
 ('ace','Ass','mit dem Aufschlag punkten','',3,'sport'),
 ('to trap','annehmen','','',4,'sport'),
 ('to assist','auflegen','stellen','helfen',2,'sport'),
 ('to attack','angreifen','attackieren','',1,'sport'),
 ('to score','punkten','treffen','',2,'sport'),
 ('defense','Verteidigung','Abwehr','',2,'sport'),
 ('pass','Zuspiel','Pass','',1,'sport'),
 ('server','Aufschläger','Angabenmacher','',3,'sport'),
 ('substitute','Auswechselspieler','Ersatzspieler','',3,'sport'),
 ('court','Spielfeld','','',3,'sport'),
 ('to spike','schmettern','schlagen','',3,'sport'),
 ('spiker','Angreifer','Offensivspieler','',4,'sport'),
 ('to set','pritschen','auflegen','stellen',2,'sport'),
 ('to bump','baggern','','',3,'sport'),
 ('foul/ fault','Foul','Fehler','Vergehen',1,'sport'),
 ('set','Satz','','',2,'sport'),
 ('service','Aufschlag','','',3,'sport'),
 ('line','Linie','','',1,'sport'),
 ('audience','Zuschauer','','',3,'sport'),
 ('jersey','Trikot','','',4,'sport'),
 ('volleyball','Volleyball','','',1,'sport'),
 ('climb','klettern','','',1,'sport'),
 ('(to) secure','sichern','','',2,'sport'),
 ('rope','Seil','','',3,'sport'),
 ('(to) boulder','bouldern','','',4,'sport'),
 ('strap/belt','Gürtel','','',5,'sport'),
 ('coach','Trainer','','',1,'sport'),
 ('fun','Freude','Spaß','',2,'sport'),
 ('friends','Freunde','','',1,'sport'),
 ('climbing clutches','Klettergriffe','','',3,'sport'),
 ('climbing shoes','Kletterschuhe','','',2,'sport'),
 ('sportswear','Sportkleidung','','',1,'sport'),
 ('knot','Schlaufe','Knoten','',5,'sport'),
 ('hook','Karabiner','','',5,'sport'),
 ('climbing hall','Kletterhalle','','',3,'sport'),
 ('climbing church','Kletterkirche','','',5,'sport'),
 ('protection device','Sicherungsgerät','','',4,'sport'),
 ('nut (climbing)','Klemmkeil','','',4,'sport'),
 ('climbing helmet','Kletterhelm','','',3,'sport'),
 ('gloves','Handschuhe','','',4,'sport'),
 ('alpin climbing','Alpinklettern','','',3,'sport'),
 ('sport climbing','Sportklettern','','',2,'sport'),
 ('fear','Angst','','',1,'sport'),
 ('big wall','große Wand','hohe Wand','',4,'sport'),
 ('loop','Schleife','Schlinge','Schlaufe',5,'sport'),
 ('height','Höhe','','',2,'sport'),
 ('lettuce','Salat','Salatkopf','',2,'food'),
 ('vegetables','Gemüse','','',2,'food'),
 ('dressing','Dressing','Salatsoße','Salatsauce',1,'food'),
 ('cucumber','Gurke','','',3,'food'),
 ('tomato','Tomate','','',1,'food'),
 ('onion','Zwiebel','Lauch','',4,'food'),
 ('to cube','würfeln','in Würfel schneide','',5,'food'),
 ('corn','Mais','','',2,'food'),
 ('pepper','Paprika','Pfeffer','',3,'food'),
 ('olive oil','Olivenöl','','',1,'food'),
 ('vinegar','Essig','','',4,'food'),
 ('herbs','Kräuter','','',4,'food'),
 ('to chop','hacken','','',5,'food'),
 ('to roast','braten','','',4,'food'),
 ('to steam','dünsten','','',5,'food'),
 ('eggplant','Aubergine','','',5,'food'),
 ('garlic','Knoblauch','','',2,'food'),
 ('pumpkin','Kürbis','','',3,'food'),
 ('potato','Kartoffel','Erdapfel','',2,'food'),
 ('cauliflower','Blumenkohl','','',4,'food'),
 ('cabbage','Kohl','','',3,'food'),
 ('broccoli','Brokkoli','','',1,'food'),
 ('mushrooms','Pilze','','',3,'food'),
 ('peas','Erbsen','','',1,'food'),
 ('asparagus','Spargel','','',5,'food'),
 ('bacon','Speck','','',3,'food'),
 ('beef','Rindfleisch','','',2,'food'),
 ('chicken','Huhn','','',1,'food'),
 ('duck','Ente','','',2,'food'),
 ('ham','Schinken','','',3,'food'),
 ('lamb','Lamm','','',2,'food'),
 ('lean meat','mageres Fleisch','','',4,'food'),
 ('minced meat','Hackfleisch','','',5,'food'),
 ('pork','Schweinefleisch','','',2,'food'),
 ('salami','Salami','','',1,'food'),
 ('sausage','Wurst','Würstchen','',3,'food'),
 ('poultry','Geflügel','','',5,'food'),
 ('meat','Fleisch','','',1,'food'),
 ('turkey','Truthahn','','',4,'food'),
 ('cutlet','Kotelett','','',4,'food'),
 ('veal','Kalbfleisch','','',5,'food'),
 ('to spice','würzen','','',3,'food'),
 ('chicken leg','Hähnchenkeule','','',4,'food'),
 ('to fry','frittieren','','',3,'food'),
 ('white meat','weißes Fleisch','','',2,'food'),
 ('steak','Steak','','',1,'food'),
 ('boned meat','Fleisch ohne Knochen','','',5,'food'),
 ('roast','braten','Braten','',4,'food'),
 ('marinade','Marinade','','',1,'food'),
 ('fork','Gabel','','',1,'food'),
 ('knife','Messer','','',1,'food'),
 ('spoon','Löffel','','',1,'food'),
 ('cup','Tasse','','',1,'food'),
 ('plate','Teller','','',1,'food'),
 ('pan','Pfanne','','',2,'food'),
 ('sink','Spüle','Waschbecken','Spülbecken',2,'food'),
 ('oven','Ofen','','',2,'food'),
 ('stove','Herd','','',2,'food'),
 ('refrigerator','Kühlschrank','','',2,'food'),
 ('whisk','Schneebesen','','',3,'food'),
 ('to do the dishes','Den Abwasch machen','abwaschen','',3,'food'),
 ('grater','Reibe','Raspel','',3,'food'),
 ('rolling pin','Nudelholz','','',3,'food'),
 ('tin opener','Dosenöffner','','',3,'food'),
 ('ladle','Kelle','Schöpfkelle','Suppenkelle',4,'food'),
 ('corkscrew','Korkenzieher','','',4,'food'),
 ('saucepan','Kochtopf','','',4,'food'),
 ('oven cloth','Topflappen','','',4,'food'),
 ('strainer','Sieb','','',4,'food'),
 ('draining board','Abtropfbrett','','',5,'food'),
 ('extractor hood','Dunstabzugshaube','Abzugshaube','',5,'food'),
 ('grinder','Fleischwolf','','',5,'food'),
 ('springform pan','Springform','Kuchenform','',5,'food'),
 ('pressure cooker','Schnellkochtopf','Dampfkochtop','Damfdruckkochtopf',5,'food'),
 ('run','laufen','rennen','',1,'sport'),
 ('proteins','Proteine','Eiweiße','',1,'food'),
 ('calories','Kalorien','','',1,'food'),
 ('vitamins','Vitamine','','',1,'food'),
 ('vegan','vegan','','',1,'food'),
 ('low calorie','kalorienarm','wenig Kalorien','',1,'food'),
 ('tp lose weight','abnehmen','Gewicht verlieren','',2,'food'),
 ('vegetarian dishes','vegetarische Gerichte','','',2,'food'),
 ('clean eating','sauberes Essen','gesundes Essen','',2,'food'),
 ('low fat','niedriger Fettgehalt','','',2,'food'),
 ('health','Gesundheit','','',2,'food'),
 ('recipe ideas','Rezeptideen','','',3,'food'),
 ('fatburner','Fettverbrenner','','',3,'food'),
 ('nutritional change','Ernährungsumstellung','','',3,'food'),
 ('balanced diet','ausgewogene Diät','ausgewogene Ernährung','',3,'food'),
 ('to go shopping','einkaufen','einkaufen gehen','',3,'food'),
 ('gluten free','glutenfrei','','',4,'food'),
 ('fiber','Ballaststoffe','','',4,'food'),
 ('low carb','wenig Kohlenhydrate','','',4,'food'),
 ('green smoothie','grüner Smoothie','','',4,'food'),
 ('healthy food','gesundes Essen','gesunde Lebensmittel','',4,'food'),
 ('paleo diet','Paleo Diät','Ernährungsart die sich an der Altsteinzeit orientiert','',5,'food'),
 ('detox cure','Detox Kur','Stoppen von ungesunden Gewohnheiten','',5,'food'),
 ('to be physically fit','körperlich fit sein','','',5,'food'),
 ('chia seeds','Chia Samen','Chiasamen','Chia-Samen',5,'food'),
 ('quinoa','gesunde essbare Pflanzenart','Quinoa','',5,'food'),
 ('to bake','backen','','',1,'food'),
 ('pastry','Mehlspeise','Süßspeise','',1,'food'),
 ('flour','Mehl','','',1,'food'),
 ('sugar','Zucker','','',1,'food'),
 ('cream','Crème','Sahne','',1,'food'),
 ('to combine','kombinieren','','',1,'food'),
 ('ginger bread','Lebkuchen','','',1,'food'),
 ('to preheat','vorheizen','','',2,'food'),
 ('pudding','Pudding','','',1,'food'),
 ('dough','Teig','','',2,'food'),
 ('to knead','kneten','','',2,'food'),
 ('cooling rack','Tortengitter','','',2,'food'),
 ('to beat','schlagen','','',2,'food'),
 ('to caramelize','karamellisieren','','',2,'food'),
 ('baking pan','Backform','','',2,'food'),
 ('vanilla extract','Vanillezucker','','',2,'food'),
 ('granulated sugar','Kristallzucker','','',2,'food'),
 ('whipped cream','Schlagsahne','','',2,'food'),
 ('to whip cream','Sahne schlagen','','',2,'food'),
 ('egg yolk','Eidotter','Eigelb','',2,'food'),
 ('wafer','Oblate','','',3,'food'),
 ('batter','Teig','','',3,'food'),
 ('to whisk','schlagen','rühren','',3,'food'),
 ('custard','Vanillecreme','','',3,'food'),
 ('yeast','Germ','Hefe','',5,'food'),
 ('to sprinkle','bestreuen','streuen','',3,'food'),
 ('to glaze','glasieren','','',4,'food'),
 ('gelatine','Gelatine','','',4,'food'),
 ('parchment paper','Backpapier','','',4,'food'),
 ('puff pastry','Blätterteig','','',4,'food'),
 ('pastry bag','Spritztüte','Spritzbeutel','',5,'food'),
 ('to flambé','flambieren','','',5,'food'),
 ('convection','Umluft','Heißluft','',5,'food'),
 ('to blend','vermischen','','',5,'food'),
 ('ball','Ball','Kugel','',1,'sport'),
 ('pitch','Spielfeld','','',2,'sport'),
 ('team','Mannschaft','Team','',1,'sport'),
 ('playing time','Spielzeit','','',1,'sport'),
 ('pause','Pause','Unterbrechung','',1,'sport'),
 ('referee','Schiedsrichter','','',5,'sport'),
 ('sports discipline','Sportart','','',5,'sport'),
 ('hall','Halle','Sporthalle','',2,'sport'),
 ('tournament','Turnier','','',3,'sport'),
 ('hockey','Hockey','','',1,'sport'),
 ('stick','Schläger','','',2,'sport'),
 ('astroturf','Kunstrasen','','',5,'sport'),
 ('goal','Tor','','',2,'sport'),
 ('halfway line','Mittelline','','',2,'sport'),
 ('to pass','Passen','','',3,'sport'),
 ('mouthguard','Mundschutz','','',3,'sport'),
 ('equipment','Ausrüstung','Ausstattung','',3,'sport'),
 ('protection','Schutz','','',3,'sport'),
 ('bag','Tasche','','',4,'sport'),
 ('shoes','Schuhe','','',4,'sport'),
 ('careful','vorsichtig','umsichtig','achtsam',4,'sport'),
 ('fun','Spaß','Vergnügen','',4,'sport'),
 ('penalty','Strafe','Strafstoß','Elfmeter',5,'sport'),
 ('carbohydrates','Kohlenhydrate','','',4,'food'),
 ('healthy body','gesunder Körper','','',3,'food'),
 ('cardio','Herz','Kardio','',3,'sport'),
 ('to coach','einarbeiten','trainieren','',2,'sport'),
 ('to stretch','dehnen','strecken','',1,'sport'),
 ('muscle','Muskel','','',1,'sport'),
 ('gym','Fitnessstudio','Sporthalle','',1,'sport'),
 ('stamina','Kondition','Ausdauer','',2,'sport'),
 ('power','Kraft','Energie','',2,'sport'),
 ('jumping jack','Hampelmann','','',3,'sport'),
 ('cardiovascular system','Herz-Kreislauf-System','','',5,'sport'),
 ('to maintain weight','das Gewicht halten','Gewicht halten','',5,'food'),
 ('workout','Training','Übungseinheit','',2,'sport'),
 ('coordination','Koordination','','',2,'sport'),
 ('to live healthy','gesung leben','','',3,'sport'),
 ('to warm up','aufwärmen','','',1,'sport'),
 ('rhythm','Rhythmus','','',1,'sport'),
 ('step machine','Stepper','','',3,'sport'),
 ('dumbbell','Hantel','Kurzhantel','',5,'sport'),
 ('crunches','Bauchpressen','','',5,'sport'),
 ('muscle building','Muskelaufbau','','',4,'sport'),
 ('dietary supplement','Nahrungsergänzungsmittel','','',5,'food'),
 ('to digest sth.','etw. verdauen','etwas verdauen','verdauen',4,'food'),
 ('ambition','Ehrgeiz','','',4,'sport'),
 ('emotion','Leidenschaft','','',3,'sport'),
 ('strength','Kraft','','',2,'sport'),
 ('discipline','Disziplin','','',2,'sport'),
 ('boxing ring','Boxring','','',1,'sport'),
 ('rules','Regeln','','',2,'sport'),
 ('to fight','kämpfen','','',3,'sport'),
 ('pain','Schmerzen','Schmerz','',4,'sport'),
 ('to win','gewinnen','','',2,'sport'),
 ('to lose','verlieren','','',3,'sport'),
 ('experience','Erfahrung','','',2,'sport'),
 ('to lern','lernen','','',5,'sport'),
 ('spectator','Zuschauer','','',3,'sport'),
 ('judge','Punkterichter','','',5,'sport'),
 ('defence','Verteidigung','','',5,'sport'),
 ('tradition','Tradition','','',1,'sport'),
 ('dangerous','gefährlich','','',4,'sport'),
 ('to peel','schälen','','',3,'food'),
 ('to rasp','reiben','raspeln','',2,'food'),
 ('to add','hinzufügen','','',1,'food'),
 ('to melt','schmelzen','','',2,'food'),
 ('to wash','waschen','','',1,'food'),
 ('to pour','gießen','','',4,'food'),
 ('to taste','abschmecken','schmecken','probieren',2,'food'),
 ('cheese','Käse','','',1,'food'),
 ('curd','Quark','','',5,'food'),
 ('yoghurt','Joghurt','','',1,'food'),
 ('milk','Milch','','',1,'food'),
 ('parmesan','Parmesan','','',1,'food'),
 ('butter milk','Buttermilch','','',2,'food'),
 ('soft cheese','Weichkäse','','',2,'food'),
 ('milk powder','Milchpulver','','',1,'food'),
 ('milkshake','Milchshake','','',2,'food'),
 ('ice cream','Eiskrem','Eis','Eiscreme',2,'food'),
 ('milk roll','Milchbrötchen','','',3,'food'),
 ('pudding','Pudding','','',1,'food'),
 ('golfbag','Golftasche','','',1,'sport'),
 ('out','aus','Aus','',1,'sport'),
 ('best ball','bester Ball','','',1,'sport'),
 ('clubhouse','Clubhaus','','',1,'sport'),
 ('down','runter','unten','',1,'sport'),
 ('to serve','bedienen','','',2,'sport'),
 ('bag tag','Anhänger','','',2,'sport'),
 ('to swing','schwingen','schlagen','',2,'sport'),
 ('break','Break','brechen','',2,'sport'),
 ('golf club','Golfschläger','','',2,'sport'),
 ('bunker','Sandhindernis','Kasten','',3,'sport'),
 ('golf course','Golfbahn','Golfplatz','',3,'sport'),
 ('driving range','Übungsgelände','Übungsplatz','',3,'sport'),
 ('iron','Eisen','','',3,'sport'),
 ('fee','Gebühr','','',3,'sport'),
 ('chip','kurzer Schlag','','',4,'sport'),
 ('handicap','Spielstärke','Vorgabe','Handicap',4,'sport'),
 ('hole-in-one','Volltreffer','mit einem Schlag einlochen','',4,'sport'),
 ('hazard','Hindernis','','',5,'sport'),
 ('grain','Maserung','Getreide','',5,'sport');
